server:
  servlet:
    #修改访问项目访问路径
    context-path: /demo
mybatis:
  type-aliases-package: com.springboot.demo.model.pojo
  configuration:
    cache-enabled: true
  mapper-locations: classpath:/mapper/**.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      initial-size: 10
      #最大连接池数
      max-active: 200
      min-idle: 10
      pool-prepared-statements: true
      max-wait: 60000
      #检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
  mvc:
    static-path-pattern: /**
      #pathmatch:
    #use-suffix-pattern: true
    #use-registered-suffix-pattern: true
  resources:
    static-locations: classpath:/resources/,classpath:/templates/,classpath:/static/

  #redis
  redis:
    #redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    #redis服务器连接密码（默认为空）
    #password:
    #连接超时时间
    timeout: 10000ms
    jedis:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 1000
        #连接池最大阻塞时间（使用负值表示没有限制）
        max-wait: 1000ms
        #连接池最大空闲连接数
        max-idle: 8
        #连接池最小空闲连接数
        min-idle: 4
  servlet:
    multipart:
      max-file-size: 100
      max-request-size: 100

#分页
pagehelper:
  #指定分页插件使用哪种方言
  helper-dialect: mysql
  #当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），
  #会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true
logging:
  config: classpath:logback-spring.xml
  #path: classpath:/logs
  #file: project.log